# Generated by Django 5.1.7 on 2025-05-20 06:28

import django.core.validators
from django.db import migrations, models

import journal.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document",
                    models.FileField(
                        upload_to="MSA/documents",
                        validators=[
                            journal.models.validate_taille_fichier,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                        ],
                    ),
                ),
                ("release_date", models.DateField(verbose_name="Date de publication")),
                (
                    "cover",
                    models.ImageField(
                        upload_to="MSA/couvertures",
                        validators=[
                            journal.models.validate_taille_fichier,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            ),
                        ],
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("page_number", models.IntegerField(default=0)),
            ],
        ),
    ]
