# Generated by Django 6.0.3 on 2026-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='number',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
