# Generated by Django 6.0.3 on 2026-06-24 14:32

import django.core.validators
from django.db import migrations, models

import journal.models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_alter_journal_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="cover",
            field=models.ImageField(
                upload_to="MSA/couvertures",
                validators=[
                    journal.models.validate_taille_fichier,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "webp"]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="release_date",
            field=models.DateField(db_index=True, verbose_name="Date de publication"),
        ),
    ]
