image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  DJANGO_SETTINGS_MODULE: "app.settings"

cache:
  paths:
    - .pip-cache/
    - venv/

stages:
  - test
  - lint
  - deploy

before_script:
  - python -V
  - apt-get update && apt-get install -y --no-install-recommends libmagic1 && rm -rf /var/lib/apt/lists/*
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install coverage

test:
  stage: test
  script:
    - coverage run --source=. manage.py test
    - coverage report -m
    - coverage xml -o coverage.xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
    when: always

lint:
  stage: lint
  script:
    - pip install flake8 black isort
    - flake8 . --exclude=venv,env,*/migrations/*,*/tests.py
    - black . --check --exclude 'venv|env|migrations|tests\.py'
    - isort . --check-only --skip venv --skip env --skip migrations --skip tests.py

deploy:
  stage: deploy
  script:
    - echo "Déploiement en production"
    # Ajoute ici tes commandes de déploiement
  only:
    - main
  environment:
    name: production
  when: manual

# Configuration GitLab CI/CD pour GitLab Pages avec MkDocs
# DÉSACTIVÉ - Documentation privée via GitLab Wiki
# pages:
#   stage: deploy
#   image: python:3.10-alpine
#   before_script:
#     - pip install mkdocs mkdocs-material
#   script:
#     # Générer le site avec MkDocs
#     - mkdocs build --site-dir public
#     # Ajouter un fichier .htaccess pour l'authentification (si nécessaire)
#     - echo "AuthType Basic" > public/.htaccess
#     - echo "AuthName 'Documentation CCSA'" >> public/.htaccess
#     - echo "AuthUserFile /path/to/.htpasswd" >> public/.htaccess
#     - echo "Require valid-user" >> public/.htaccess
#   artifacts:
#     paths:
#       - public
#     expire_in: 30 days
#   only:
#     - main
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main" 