# Generated by Django 5.1.7 on 2025-05-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("icon", models.CharField(max_length=1000, verbose_name="Icon")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OBLIGATOIRE", "Obligatoire"),
                            ("OPTIONNELLE", "Optionnelle"),
                            ("FACULTATIVE", "Facultative"),
                        ],
                        default="FACULTATIVE",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("is_big", models.BooleanField(default=False, verbose_name="Is Big")),
            ],
            options={
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
            },
        ),
    ]
