# Generated by Django 6.0.3 on 2026-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='category',
            field=models.CharField(choices=[('OBLIGATOIRE', 'Obligatoire'), ('OPTIONNELLE', 'Optionnelle'), ('FACULTATIVE', 'Facultative'), ('TRANSFEREE', 'Transférées')], default='FACULTATIVE', max_length=20, verbose_name='Category'),
        ),
    ]
