# Generated by Django 6.0.3 on 2026-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competences", "0002_alter_competence_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competence",
            name="category",
            field=models.CharField(
                choices=[
                    ("OBLIGATOIRE", "Obligatoire"),
                    ("OPTIONNELLE", "Optionnelle"),
                    ("FACULTATIVE", "Facultative"),
                    ("TRANSFEREE", "Transférées"),
                ],
                db_index=True,
                default="FACULTATIVE",
                max_length=20,
                verbose_name="Category",
            ),
        ),
    ]
