# Generated by Django 5.1.7 on 2025-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="content",
            field=models.TextField(verbose_name="Description"),
        ),
    ]
