# Generated by Django 6.0.3 on 2026-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_service_audit_and_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Description longue du service",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.TextField(
                help_text="Code SVG inline validé côté serveur (max 5000 caractères).",
                verbose_name="Icône SVG",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(
                help_text="Titre affiché du service",
                max_length=100,
                verbose_name="Titre",
            ),
        ),
    ]
