# Generated by Django 5.1.7 on 2025-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Les groupes auxquels appartient cet utilisateur. Un utilisateur obtiendra toutes les permissions accordées à chacun de ses groupes.",
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.group",
                verbose_name="groupes",
            ),
        ),
    ]
