# Generated by Django 6.0.3 on 2026-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_groups"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["-is_superuser", "-is_staff", "username"],
                name="user_admin_list_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username", ""), _negated=True),
                fields=("username",),
                name="unique_nonempty_username",
            ),
        ),
    ]
