# Generated by Django 5.1.7 on 2025-05-20 06:28

import django.core.validators
from django.db import migrations, models

import journal.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompteRendu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Conseil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.TimeField()),
                ("place", models.CharField(max_length=100)),
                (
                    "day_order",
                    models.FileField(
                        blank=True,
                        upload_to="comptes-rendus/ordre-du-jour/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                            journal.models.validate_taille_fichier,
                        ],
                    ),
                ),
            ],
        ),
    ]
