# Generated by Django 5.1.7 on 2026-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptes_rendus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conseil",
            name="place",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
