# Generated by Django 6.0.3 on 2026-04-27 09:59

import django.core.validators
import django.db.models.deletion
import journal.models
from django.db import migrations, models


def migrate_day_orders(apps, schema_editor):
    Conseil = apps.get_model('comptes_rendus', 'Conseil')
    DocumentConseil = apps.get_model('comptes_rendus', 'DocumentConseil')
    for conseil in Conseil.objects.all():
        if conseil.day_order:
            DocumentConseil.objects.create(
                conseil=conseil,
                file=conseil.day_order,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('comptes_rendus', '0002_alter_conseil_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comptes-rendus/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), journal.models.validate_taille_fichier])),
                ('title', models.CharField(blank=True, help_text='Titre personnalisé (laisser vide pour utiliser le nom du fichier)', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conseil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='comptes_rendus.conseil')),
            ],
            options={
                'ordering': ['file'],
            },
        ),
        migrations.RunPython(migrate_day_orders, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='conseil',
            name='day_order',
        ),
    ]