# Generated by Django 6.0.3 on 2026-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptes_rendus", "0003_remove_conseil_day_order_documentconseil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conseil",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
