# Generated by Django 6.0.3 on 2026-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptes_rendus", "0004_alter_conseil_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="compterendu",
            name="singleton",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddIndex(
            model_name="conseil",
            index=models.Index(fields=["date", "hour"], name="conseil_date_hour_idx"),
        ),
        migrations.AddConstraint(
            model_name="compterendu",
            constraint=models.UniqueConstraint(
                fields=("singleton",),
                name="comptes_rendus_compterendu_singleton_unique",
            ),
        ),
    ]
