# Generated by Django 5.1.7 on 2025-05-20 06:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import journal.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conseil_communautaire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="bureau_commu/documents/",
                        validators=[
                            journal.models.validate_taille_fichier,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("organigramme", "Organigramme"),
                            ("calendrier", "Calendrier"),
                        ],
                        default="organigramme",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="Elus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("rank", models.IntegerField(default=0)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Vice-Président", "Vice-Président"),
                            ("Président", "Président"),
                        ],
                        default="Vice-Président",
                        max_length=50,
                        verbose_name="Rôle",
                    ),
                ),
                ("function", models.CharField(max_length=100)),
                (
                    "picture",
                    models.ImageField(
                        upload_to="bureau_commu/elus/",
                        validators=[
                            journal.models.validate_taille_fichier,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            ),
                        ],
                        verbose_name="Photo de l'élu",
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conseil_communautaire.conseilville",
                    ),
                ),
            ],
        ),
    ]
