# Generated by Django 5.1.7 on 2025-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bureau_communautaire", "0002_elus_linked_commission"),
        ("commissions", "0002_alter_commission_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elus",
            name="linked_commission",
        ),
        migrations.AddField(
            model_name="elus",
            name="linked_commission",
            field=models.ManyToManyField(
                blank=True, related_name="elus", to="commissions.commission"
            ),
        ),
    ]
