# Generated by Django 5.1.7 on 2026-02-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bureau_communautaire", "0003_elus_multi_commissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elus",
            name="function",
            field=models.CharField(max_length=200),
        ),
    ]
