# Generated by Django 6.0.3 on 2026-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau_communautaire', '0004_alter_elus_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('bureau-communautaire', 'Bureau Communautaire')], max_length=50, unique=True, verbose_name='Page')),
                ('is_active', models.BooleanField(default=True, verbose_name='Page active')),
                ('maintenance_message', models.TextField(default='La page est en cours de mise à jour.', help_text='Message affiché lorsque la page est désactivée.', verbose_name='Message de maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statut de page',
                'verbose_name_plural': 'Statuts de pages',
            },
        ),
    ]
