# Generated by Django 6.0.3 on 2026-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau_communautaire', '0005_pagestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elus',
            name='function',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
