# Generated by Django 6.0.3 on 2026-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau_communautaire', '0006_alter_elus_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestatus',
            name='page_name',
            field=models.CharField(choices=[('bureau-communautaire', 'Bureau Communautaire'), ('commissions', 'Commissions')], max_length=50, unique=True, verbose_name='Page'),
        ),
    ]
