# Generated by Django 6.0.3 on 2026-04-24 14:12

import django.core.validators
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau_communautaire', '0007_alter_pagestatus_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elus',
            name='picture',
            field=models.ImageField(upload_to='bureau_commu/elus/', validators=[journal.models.validate_taille_fichier, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name="Photo de l'élu"),
        ),
    ]
