# Generated by Django 6.0.3 on 2026-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bureau_communautaire", "0008_alter_elus_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elus",
            name="role",
            field=models.CharField(
                choices=[
                    ("Vice-Président", "Vice-Président"),
                    ("Président", "Président"),
                ],
                db_index=True,
                default="Vice-Président",
                max_length=50,
                verbose_name="Rôle",
            ),
        ),
    ]
