# Generated by Django 6.0.3 on 2026-06-30 10:26

import django.core.validators
from django.db import migrations, models

import app.validators
import journal.models


class Migration(migrations.Migration):
    dependencies = [
        ("bureau_communautaire", "0009_alter_elus_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elus",
            name="picture",
            field=models.ImageField(
                upload_to="bureau_commu/elus/",
                validators=[
                    journal.models.validate_taille_fichier,
                    app.validators.validate_image_mime,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "webp"]
                    ),
                ],
                verbose_name="Photo de l'élu",
            ),
        ),
    ]
