# Generated by Django 6.0.3 on 2026-06-30 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bureau_communautaire", "0010_alter_elus_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="elus",
            options={
                "ordering": ["role", "rank", "last_name", "first_name"],
                "verbose_name": "Élu",
                "verbose_name_plural": "Élus",
            },
        ),
    ]
