# Generated by Django 5.1.7 on 2026-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("url", models.CharField(max_length=200, verbose_name="URL")),
                (
                    "content",
                    models.TextField(
                        help_text="Contenu textuel de la page", verbose_name="Contenu"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Page statique",
                "verbose_name_plural": "Pages statiques",
                "ordering": ["title"],
            },
        ),
    ]
