# Generated by Django 6.0.3 on 2026-06-25 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Dépublier exclut la page du sitemap et de la recherche.', verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='url',
            field=models.CharField(db_index=True, help_text="URL relative (/chemin/) ou nom d'URL Django (namespace:name).", max_length=200, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='staticpage',
            index=models.Index(fields=['is_published', 'title'], name='home_static_is_publ_78e960_idx'),
        ),
        migrations.AddConstraint(
            model_name='staticpage',
            constraint=models.UniqueConstraint(fields=('url',), name='home_staticpage_url_unique'),
        ),
    ]
