# Generated by Django 6.0.3 on 2026-07-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_staticpage_created_at_staticpage_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PLUISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singleton", models.BooleanField(default=True, editable=False)),
                (
                    "modification_simplifiee_1_visible",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez pour rendre la page accessible et afficher sa carte sur la page PLUi.",  # noqa: E501
                        verbose_name="Modification Simplifiée n°1 visible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres PLUi",
                "verbose_name_plural": "Paramètres PLUi",
            },
        ),
    ]
