# Generated by Django 5.1.7 on 2025-05-20 06:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import journal.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conseil_communautaire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActeLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("description", models.TextField(max_length=500)),
                (
                    "file",
                    models.FileField(
                        upload_to="communes/actes_locaux/",
                        validators=[
                            journal.models.validate_taille_fichier,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            ),
                        ],
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conseil_communautaire.conseilville",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
