# Generated by Django 5.1.7 on 2025-06-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communes_membres", "0001_initial"),
        ("conseil_communautaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actelocal",
            name="commune",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acte_local",
                to="conseil_communautaire.conseilville",
            ),
        ),
    ]
