# Generated by Django 5.1.7 on 2025-05-20 06:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import journal.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConseilVille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "mayor_sex",
                    models.CharField(
                        choices=[("Mme.", "Madame"), ("M.", "Monsieur")],
                        default="M.",
                        max_length=7,
                    ),
                ),
                ("mayor_first_name", models.CharField(max_length=20)),
                ("mayor_last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=5)),
                ("phone_number", models.CharField(max_length=10)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="communes/images/",
                        validators=[
                            journal.models.validate_taille_fichier,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            ),
                        ],
                    ),
                ),
                ("slogan", models.CharField(blank=True, max_length=100, null=True)),
                ("nb_habitants", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ConseilMembre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("is_suppleant", models.BooleanField(default=False)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("Madame", "Madame"), ("Monsieur", "Monsieur")],
                        default="Monsieur",
                        max_length=8,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conseil_communautaire.conseilville",
                    ),
                ),
            ],
            options={
                "unique_together": {("first_name", "last_name", "city")},
            },
        ),
    ]
