# Generated by Django 5.1.7 on 2025-06-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0001_initial"),
        ("conseil_communautaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conseilmembre",
            name="linked_commission",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="commissions.commission",
            ),
        ),
    ]
