# Generated by Django 6.0.3 on 2026-04-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conseil_communautaire', '0002_conseilmembre_linked_commission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conseilmembre',
            unique_together=set(),
        ),
    ]
