# Generated by Django 6.0.3 on 2026-04-24 08:53

import django.core.validators
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil_communautaire', '0004_alter_conseilmembre_linked_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilmembre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membres/photos/', validators=[journal.models.validate_taille_fichier, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
