# Generated by Django 6.0.3 on 2026-04-27 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil_communautaire', '0006_alter_conseilmembre_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilmembre',
            name='photo_position_x',
            field=models.IntegerField(default=50, help_text='Position horizontale de la photo (0 = gauche, 50 = centre, 100 = droite)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Position X (%)'),
        ),
        migrations.AddField(
            model_name='conseilmembre',
            name='photo_position_y',
            field=models.IntegerField(default=50, help_text='Position verticale de la photo (0 = haut, 50 = centre, 100 = bas)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Position Y (%)'),
        ),
    ]
