# Generated by Django 6.0.3 on 2026-04-27 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil_communautaire', '0007_conseilmembre_photo_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilmembre',
            name='photo_zoom',
            field=models.IntegerField(default=100, help_text='Zoom de la photo (50% = plus petit, 100% = taille normale, 200% = plus grand)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='Zoom (%)'),
        ),
    ]
