# Generated by Django 6.0.3 on 2026-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conseil_communautaire", "0008_conseilmembre_photo_zoom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conseilmembre",
            name="is_suppleant",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
