# Generated by Django 5.1.7 on 2026-02-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        help_text="Texte affiché sur le bouton",
                        max_length=100,
                        verbose_name="Titre du lien",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Adresse complète du lien (https://...)",
                        verbose_name="URL",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("twitter", "Twitter/X"),
                            ("tiktok", "TikTok"),
                            ("snapchat", "Snapchat"),
                            ("pinterest", "Pinterest"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("line", "Line"),
                            ("discord", "Discord"),
                            ("twitch", "Twitch"),
                            ("site-web", "Site web"),
                            ("email", "Email"),
                            ("telephone", "Téléphone"),
                            ("dossier", "Dossier/Documents"),
                            ("fichier", "Fichier/PDF"),
                            ("calendrier", "Calendrier/Événement"),
                            ("carte", "Carte/Localisation"),
                            ("contact", "Contact"),
                            ("info", "Information"),
                            ("question", "FAQ/Aide"),
                            ("lien", "Lien générique"),
                            ("etoile", "Favoris/Important"),
                            ("cœur", "Cœur/Santé"),
                            ("chat", "Chat/Message"),
                            ("video", "Vidéo"),
                            ("musique", "Musique/Audio"),
                            ("photo", "Photo/Galerie"),
                            ("news", "Actualités"),
                            ("alerte", "Alerte/Notification"),
                            ("check", "Validation/Check"),
                            ("telecharger", "Téléchargement"),
                            ("externe", "Lien externe"),
                        ],
                        default="lien",
                        help_text="Icône affichée à côté du titre",
                        max_length=20,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Les liens sont affichés par ordre croissant",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour masquer le lien",
                        verbose_name="Actif",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lien",
                "verbose_name_plural": "Liens",
                "ordering": ["ordre", "titre"],
            },
        ),
    ]
