# Generated by Django 6.0.3 on 2026-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linktree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lien",
            name="actif",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Décocher pour masquer le lien",
                verbose_name="Actif",
            ),
        ),
    ]
