# Generated by Django 5.1.7 on 2026-02-16 09:45

import django.core.validators
import django.db.models.deletion
import partenaires.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriePartenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Catégorie de partenaire",
                "verbose_name_plural": "Catégories de partenaires",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Partenaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "type_partenaire",
                    models.CharField(
                        choices=[
                            ("contribution", "Contributions"),
                            ("financement", "Financement / Convention"),
                            ("subvention", "Subventions à"),
                        ],
                        max_length=20,
                        verbose_name="Type de partenariat",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partenaires/logos/",
                        validators=[
                            partenaires.models.validate_taille_fichier,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "webp", "svg"]
                            ),
                        ],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partenaires.categoriepartenaire",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["type_partenaire", "ordre", "nom"],
            },
        ),
    ]
