# Generated by Django 5.1.7 on 2026-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partenaires", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partenaire",
            name="lien_interne",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Accueil"),
                    ("presentation", "Présentation"),
                    ("equipe", "Équipe"),
                    ("mobilite", "Mobilité"),
                    ("habitat", "Habitat"),
                    ("dev_eco", "Développement économique"),
                    ("tourisme", "Tourisme"),
                    ("pnra", "Parc Naturel Régional"),
                    ("maisons_sante", "Maisons de santé"),
                    ("mutuelle", "Mutuelle intercommunautaire"),
                    ("contrat_local_sante", "Contrat local santé"),
                    ("mediapass", "Médi@'pass"),
                    ("plui", "PLUi"),
                    ("projet_plui", "Projet PLUi"),
                    ("documents_plui", "Documents PLUi"),
                    ("marches_publics", "Marchés publics"),
                    ("mentions_legales", "Mentions légales"),
                    ("politique_confidentialite", "Politique de confidentialité"),
                    ("cookies", "Politique de cookies"),
                    ("plan_du_site", "Plan du site"),
                    ("accessibilite", "Accessibilité"),
                    ("kit_logos", "Kit de logos"),
                    ("guide_eco_citoyen", "Guide éco-citoyen"),
                    ("collecte_dechets", "Collecte des déchets"),
                    ("encombrants", "Encombrants"),
                    ("dechetteries", "Déchèteries"),
                    ("communes-membres:commune", "Page commune (nécessite un slug)"),
                    ("commissions:commissions", "Commissions"),
                    ("competences:competences", "Compétences"),
                    ("comptes_rendus:comptes_rendus", "Comptes rendus"),
                    ("bureau-communautaire:elus", "Élus du bureau communautaire"),
                    ("journal:journal_list", "Journal"),
                    ("partenaires:partenaires", "Partenaires"),
                    ("linktree:linktree", "Liens utiles"),
                ],
                max_length=50,
                verbose_name="Page interne",
            ),
        ),
        migrations.AddField(
            model_name="partenaire",
            name="type_lien",
            field=models.CharField(
                choices=[
                    ("externe", "Lien externe (URL)"),
                    ("interne", "Lien interne (page du site)"),
                ],
                default="externe",
                max_length=10,
                verbose_name="Type de lien",
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="site_web",
            field=models.URLField(blank=True, verbose_name="Site web (URL externe)"),
        ),
    ]
