# Generated by Django 5.1.7 on 2026-02-16 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partenaires", "0002_partenaire_lien_interne_partenaire_type_lien_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partenaire",
            options={
                "ordering": ["categorie__ordre", "ordre", "nom"],
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
            },
        ),
        migrations.RemoveField(
            model_name="partenaire",
            name="type_partenaire",
        ),
    ]
