# Generated by Django 5.1.7 on 2026-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partenaires", "0003_alter_partenaire_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partenaire",
            name="couleur_fond",
            field=models.CharField(
                choices=[
                    ("#f3f4f6", "Gris très clair (par défaut)"),
                    ("#ffffff", "Blanc"),
                    ("#e5e7eb", "Gris clair"),
                    ("#9ca3af", "Gris"),
                    ("#4b5563", "Gris foncé"),
                    ("#dbeafe", "Bleu très clair"),
                ],
                default="#f3f4f6",
                max_length=7,
                verbose_name="Couleur de fond du logo",
            ),
        ),
    ]
