# Generated by Django 5.1.7 on 2026-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partenaires", "0004_partenaire_couleur_fond"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriepartenaire",
            name="type_section",
            field=models.CharField(
                choices=[("normal", "Normal"), ("subvention", "Subvention")],
                default="normal",
                max_length=20,
                verbose_name="Type de section",
            ),
        ),
    ]
