# Generated by Django 6.0.3 on 2026-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partenaires", "0005_categoriepartenaire_type_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriepartenaire",
            name="active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Actif"
            ),
        ),
        migrations.AlterField(
            model_name="categoriepartenaire",
            name="ordre",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="categoriepartenaire",
            name="type_section",
            field=models.CharField(
                choices=[("normal", "Normal"), ("subvention", "Subvention")],
                db_index=True,
                default="normal",
                max_length=20,
                verbose_name="Type de section",
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Actif"
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="ordre",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="Ordre d'affichage"
            ),
        ),
    ]
