# Generated by Django 5.1.7 on 2026-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_query_length",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Nombre minimum de caractères pour une recherche",
                        verbose_name="Longueur minimale de recherche",
                    ),
                ),
                (
                    "max_query_length",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Nombre maximum de caractères pour une recherche",
                        verbose_name="Longueur maximale de recherche",
                    ),
                ),
                (
                    "results_per_page",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Nombre de résultats affichés par page",
                        verbose_name="Résultats par page",
                    ),
                ),
                (
                    "highlight_search_terms",
                    models.BooleanField(
                        default=True,
                        help_text="Mettre en évidence les termes recherchés dans les résultats",
                        verbose_name="Surligner les termes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de recherche",
                "verbose_name_plural": "Configuration de recherche",
            },
        ),
    ]
