# Generated by Django 6.0.3 on 2026-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_rename_searchconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchconfigmodel",
            name="singleton",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="searchconfigmodel",
            name="results_per_page",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Nombre de résultats affichés par page",
                verbose_name="Résultats affichés par page",
            ),
        ),
    ]
