# Generated by Django 5.1.7 on 2026-02-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        default="j.brechoire@gmail.com",
                        help_text="Email qui recevra les notifications de sauvegarde (succès et échec)",
                        max_length=254,
                        verbose_name="Email de notification",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre de backup",
                "verbose_name_plural": "Paramètres de backup",
            },
        ),
    ]
