# Generated by Django 6.0.3 on 2026-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupsettings",
            name="singleton",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
