# Generated by Django 5.1.7 on 2025-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="icon",
            field=models.TextField(
                help_text="Code SVG complet de l'icône", verbose_name="Icon SVG"
            ),
        ),
    ]
