# Generated by Django 6.0.3 on 2026-05-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commission_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Compétence')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='commissions.commission')),
            ],
            options={
                'verbose_name': 'Compétence de commission',
                'verbose_name_plural': 'Compétences de commission',
                'ordering': ['order', 'title'],
            },
        ),
    ]
