# Generated by Django 6.0.3 on 2026-06-24 14:32

import django.core.validators
from django.db import migrations, models

import journal.models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0003_commissioncompetence"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="singleton",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to="commissions/documents/",
                validators=[
                    journal.models.validate_taille_fichier,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "png",
                            "jpg",
                            "jpeg",
                            "webp",
                            "xls",
                            "xlsx",
                            "doc",
                            "docx",
                        ]
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="mandat",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_year__gt", models.F("start_year"))),
                name="mandat_end_year_after_start_year",
            ),
        ),
    ]
