# Generated by Django 5.1.7 on 2025-06-17 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("semestriels", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="IsDateCorrect",
        ),
    ]
