# Generated by Django 5.1.7 on 2025-09-01 08:14

import django.core.validators
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semestriels", "0002_delete_event_delete_isdatecorrect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semestrielpage",
            name="picture",
            field=models.ImageField(
                upload_to="semestriels/image",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"],
                        message="Le fichier doit être une image au format JPG, JPEG, PNG.",
                    ),
                    journal.models.validate_taille_fichier,
                ],
            ),
        ),
    ]
