# Generated by Django 6.0.3 on 2026-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semestriels", "0004_semestrielpage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="semestrielpage",
            name="singleton",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name="semestrielpage",
            constraint=models.UniqueConstraint(
                fields=("singleton",),
                name="semestriels_semestrielpage_singleton_unique",
            ),
        ),
    ]
